[project]
name = "dynette"
version = "1.0.0"
description = "YunoHost DynDNS Server"
readme = "README.md"
license = { text = "AGPL-3.0-only" }
authors = [
    { name = "YunoHost", email = "yunohost@yunohost.org" }
]
urls.Repository = "https://github.com/yunohost/dynette"

requires-python = ">=3.13"
dependencies = [
    "bcrypt~=5.0",
    "Flask~=3.0",
    "Flask-Limiter~=3.0",
    "gunicorn~=23.0",
    "Jinja2~=3.1",
    "pydantic~=2.12",
    "PyYAML~=6.0",
    "redis~=7.0",
    "werkzeug~=3.0",
    "zonefile-parser @ git+https://github.com/yunohost/zonefile-parser@support_multiple_origin",
    # shodohflo dependencies
    "dnspython",
    "sqlalchemy>=2.0.48",
]

[dependency-groups]
test = [
    "ruff",
    "mypy",
    "pytest",
]
client = [
    "requests",
]
monitor = [
    "shodohflo @ git+https://github.com/Salamandar/shodohflo@pyproject",
    "requests",
]

[project.scripts]
dynettectl = "dynette.dynettectl:main"
regen_named_conf = "dynette.regen_named_conf:main"
dnstap_monitor = "dynette.dnstap_monitor:main"
migrate_old_zones = "dynette.migrate_old_zones:main"

[tool.uv]
package = true

[tool.ruff]
line-length = 88
lint.select = ["ALL"]
lint.ignore = [
    "ANN401",   # any-type
    "COM812",   # missing-trailing-comma
    "CPY",      # Copyrights
    "D",        # Docstrings
    "EXE001",   # Shebang is present but file is not executable
    "EM101",    # Raise messages
    "EM102",
    "ERA001",   # Commented out code
    "C901",     # Complexity
    "TC002",    # Move third-party import into a type-checking block
    "PLR0911",  # too-many-return-statements
    "PLR0912",  # too-many-branches
    "PLR0913",  # too-many-arguments
    "PLR0915",  # too-many-statements
    "PLR2004",  # magic-value-comparison
    "S101",     # Use of assert
    "S603",     # `subprocess` call: check for execution of untrusted input
    "S607",     # Starting a process with a partial executable path
    "T201",     # Use of print
    "TRY003",   # raise-vanilla-args
    "UP009",    # utf8-encoding-declaration
]

[tool.mypy]
strict = true
